build:
  uri: https://github.com/jboss-developer/jboss-eap-quickstarts.git
  ref: 8.0.x
  contextDir: remote-helloworld-mdb
deploy:
  replicas: 1
  env:
    # Env vars to connect to Artemis
    - name: JBOSS_MESSAGING_CONNECTOR_HOST
      value: "artemis"
    - name: JBOSS_MESSAGING_CONNECTOR_PORT
      value: "61616"